var e=["This should cycle through some dumb phrases.","Give me money please.","I make things.","Wow this website looks good!","I AM TOTALLY NOT A ROBOT.","Pretty good.","Do me a flavor and send an email my way.","I\u2019m ugly but at least my eyes are green.","You should give me a job.","I\u2019m probably locked in my room playing with LEGO.","I don\u2019t even see the code. All I see is blonde, brunette, redhead.","It\u2019s a Unix system, I know this.","Did I mention that I would like a job?",":(){:|:&};:\ufeff",
"One job please!","Some days even my lucky rocket ship underpants don\u2019t help.","Christopher Dombroccoli.","HTML is the best programming language.","People who put noses in smiley faces are heathens.",":-)","I'm a genius. I build robots for fun.","Programmer Extraordinaire.","I'm pretty sure we're all in a simulation.","My favorite color is orange.","Have a nice day!","I just finished a jigsaw puzzle. The package said 5+ years but it only took me 2 months.","It's a doggy dog world out there.",
"I should have bought Bitcoin.","I use <i>coding</i> and <i>algorithms</i> to solve problems.","The language I like to use most when programming is profanity.","I'm probably showing this to you during an interview.","if ( !isWorking() ) { <br>&emsp;work();<br>}","Arrays should start at 2.",'"This shouldn\'t be working."'],r=[];
function t(){var a=document.getElementById("ticker");if(a.parentElement.querySelector(":hover")!==a){a.className+="fade";0==e.length&&(e=r,r=[]);var b=e.splice(Math.floor(Math.random()*e.length),1);r.push(b);var d=Math.floor(1E3*parseFloat(window.getComputedStyle(a).transitionDuration));setTimeout(function(){a.classList.remove("fade");a.innerHTML=b},d)}}var u;window.onload=function(){setInterval(t,3E3);u=document.getElementsByClassName("scrollfade")};
window.onscroll=function(){if(u)for(var a=0;a<u.length;a++){var b=u[a],d=b.offsetHeight;d=(d-pageYOffset)/d;b.style.opacity=0>d?0:1<d?1:d*d}};var v=[];w();function w(){var a=new XMLHttpRequest;a.open("GET","model/network.dat");a.responseType="arraybuffer";a.onload=function(){var b=a.response;v.length=5;(v[0]=[]).length=784;(v[2]=[]).length=40;(v[4]=[]).length=10;b=new Float32Array(b);v[1]=b.slice(0,31360);v[3]=b.slice(31360,62720)};a.send()}
window.addEventListener("load",function(){for(var a=document.getElementsByClassName("digitsAI"),b=0;b<a.length;b++){var d=function(){m.fillRect(0,0,g.width,g.height);B(g,q);A.innerText=""},f=function(h){h.preventDefault();x=!1;var c=q.getContext("2d");h=[];h.length=784;c=c.getImageData(0,0,28,28).data;for(var a=0;a<h.length;a++)h[a]=c[4*a]/255;for(c=0;c<h.length;c++)v[0][c]=h[c];for(c=0;c<v[2].length;c++)v[2][c]=0;for(c=h=0;c<v[0].length;c++)for(a=0;a<v[2].length;a++)v[2][a]+=v[0][c]*v[1][h],h++;
for(c=0;c<v[2].length;c++)v[2][c]=1/(1+Math.exp(-v[2][c]));for(c=0;c<v[4].length;c++)v[4][c]=0;for(c=h=0;c<v[2].length;c++)for(a=0;a<v[4].length;a++)v[4][a]+=v[2][c]*v[3][h],h++;for(c=0;c<v[4].length;c++)v[4][c]=1/(1+Math.exp(-v[4][c]));h=v[4];c=h[0];a=0;for(var b=1;b<h.length;b++)h[b]>c&&(c=h[b],a=b);A.innerText=a},k=function(a,c,b){a.preventDefault();x&&(m.moveTo(y,z),m.lineTo(c,b),m.closePath(),m.stroke(),y=c,z=b,B(g,q))},l=function(a,c,b){a.preventDefault();x=!0;y=c;z=b;m.beginPath();m.ellipse(c,
b,0,0,0,0,Math.PI+Math.PI);m.closePath();m.stroke();m.moveTo(c,b);m.beginPath();B(g,q)},n=a[b],g=n.getElementsByClassName("digitInput")[0];C(g);var p=n.getElementsByClassName("digitClear")[0];p.innerText="clear";var q=n.getElementsByClassName("digitRaw")[0];q.width=28;q.height=28;var A=n.getElementsByClassName("digitGuess")[0],m=g.getContext("2d");n=13*window.devicePixelRatio;m.strokeStyle="#FFFFFF";m.lineJoin="round";m.lineCap="round";m.lineWidth=n+n;var x=!1,y=0,z=0;g.addEventListener("mousedown",
function(a){l(a,a.pageX-this.offsetLeft,a.pageY-this.offsetTop)});g.addEventListener("touchstart",function(a){l(a,a.targetTouches[0].pageX-this.offsetLeft,a.targetTouches[0].pageY-this.offsetTop)});g.addEventListener("mousemove",function(a){k(a,a.pageX-this.offsetLeft,a.pageY-this.offsetTop)});g.addEventListener("touchmove",function(a){k(a,a.targetTouches[0].pageX-this.offsetLeft,a.targetTouches[0].pageY-this.offsetTop)});g.addEventListener("mouseup",f);g.addEventListener("touchend",f);d();p.onclick=
d}});function C(a){var b=224*window.devicePixelRatio;a.width=b;a.height=b}function B(a,b){b.getContext("2d").drawImage(a,0,0,a.width,a.height,0,0,b.width,b.height)}
window.addEventListener("load",function(){function a(a,b){var d=new Image,f=p.dataset.src;d.onload=function(){a.parent?a.parent.replaceChild(d,a):a.src=f;b?b(a):null};d.src=f}for(var b=document.getElementsByClassName("slideshow"),d=0;d<b.length;d++){var f=b[d];f.index=0;f.a=0;var k=document.createElement("div");k.className+="selectors";var l=document.createElement("a");l.classList.toggle("prev");l.classList.toggle("selector");l.innerHTML="&#10094;";l.onclick=function(){var a=f;return function(){D(a,
--a.index)}}();k.appendChild(l);l=f.getElementsByClassName("slide").length;for(var n=0;n<l;n++){var g=document.createElement("a");g.classList.toggle("selector");g.index=n;g.innerText=n;g.onclick=function(){var a=f,b=n;return function(){a.index=b;D(a,b)}}();k.appendChild(g)}l=document.createElement("a");l.classList.toggle("next");l.classList.toggle("selector");l.innerHTML="&#10095;";l.onclick=function(){var a=f;return function(){D(a,++a.index)}}();k.appendChild(l);f.appendChild(k);k=document.createElement("div");
k.classList.toggle("caption");f.appendChild(k);D(f,0)}b=document.getElementsByTagName("img");for(d=0;d<b.length;d++){var p=b[d];p.dataset.src?a(p,function(a){a.style.filter="unset"}):p.style.filter="unset"}});
function D(a,b){var d=a.getElementsByClassName("slide"),f=d.length;b=(b%f+f)%f;f=d[b];d[a.a].style.display="";f.style.display="block";var k=a.getElementsByClassName("caption");for(d=0;d<k.length;d++)k[d].innerHTML=f.dataset.caption;f=a.getElementsByClassName("selectors");for(d=0;d<f.length;d++)k=f[d].getElementsByClassName("selector"),k[a.a+1].classList.remove("selectorActive"),k[b+1].classList.add("selectorActive");a.a=b};