window.addEventListener("load",function(){for(var a=document.getElementsByClassName("digitsAI"),e=0;e<a.length;e++){var c=function(){m.fillRect(0,0,g.width,g.height);p(g,r);B.innerText=""},f=function(h){h.preventDefault();x=!1;var d=r.getContext("2d");h=[];h.length=784;d=d.getImageData(0,0,28,28).data;for(var b=0;b<h.length;b++)h[b]=d[4*b]/255;d=t;for(b=0;b<h.length;b++)d[0][b]=h[b];for(b=0;b<d[2].length;b++)d[2][b]=0;for(b=h=0;b<d[0].length;b++)for(var a=0;a<d[2].length;a++)d[2][a]+=d[0][b]*d[1][h],
h++;for(b=0;b<d[2].length;b++)d[2][b]=1/(1+Math.exp(-d[2][b]));for(b=0;b<d[4].length;b++)d[4][b]=0;for(b=h=0;b<d[2].length;b++)for(a=0;a<d[4].length;a++)d[4][a]+=d[2][b]*d[3][h],h++;for(b=0;b<d[4].length;b++)d[4][b]=1/(1+Math.exp(-d[4][b]));h=d[4];d=h[0];b=0;for(a=1;a<h.length;a++)h[a]>d&&(d=h[a],b=a);B.innerText=b},k=function(a,d,b){a.preventDefault();x&&(m.moveTo(y,z),m.lineTo(d,b),m.closePath(),m.stroke(),y=d,z=b,p(g,r))},l=function(a,d,b){a.preventDefault();x=!0;y=d;z=b;m.beginPath();m.ellipse(d,
b,0,0,0,0,Math.PI+Math.PI);m.closePath();m.stroke();m.moveTo(d,b);m.beginPath();p(g,r)},n=a[e],g=n.getElementsByClassName("digitInput")[0];u(g);var q=n.getElementsByClassName("digitClear")[0];q.innerText="clear";var r=n.getElementsByClassName("digitRaw")[0];r.width=28;r.height=28;var B=n.getElementsByClassName("digitGuess")[0],m=g.getContext("2d");m.strokeStyle="#FFFFFF";m.lineJoin="round";m.lineCap="round";m.lineWidth=26;var x=!1,y=0,z=0;g.addEventListener("mousedown",function(a){l(a,a.pageX-this.offsetLeft,
a.pageY-this.offsetTop)});g.addEventListener("touchstart",function(a){l(a,a.targetTouches[0].pageX-this.offsetLeft,a.targetTouches[0].pageY-this.offsetTop)});g.addEventListener("mousemove",function(a){k(a,a.pageX-this.offsetLeft,a.pageY-this.offsetTop)});g.addEventListener("touchmove",function(a){k(a,a.targetTouches[0].pageX-this.offsetLeft,a.targetTouches[0].pageY-this.offsetTop)});g.addEventListener("mouseup",f);g.addEventListener("touchend",f);g.addEventListener("mouseleave",f);g.addEventListener("touchleave",
f);c();q.onclick=c}});function u(a){a.width=224;a.height=224}function p(a,e){e.getContext("2d").drawImage(a,0,0,a.width,a.height,0,0,e.width,e.height)}var t=[];v();function v(){var a=new XMLHttpRequest;a.open("GET","model/network.dat");a.responseType="arraybuffer";a.onload=function(){var e=a.response;t.length=5;(t[0]=[]).length=784;(t[2]=[]).length=40;(t[4]=[]).length=10;e=new Float32Array(e);t[1]=e.slice(0,31360);t[3]=e.slice(31360,62720)};a.send()}
var w=["This should cycle through some dumb phrases.","Give me money please.","I make things.","Wow this website looks good!","I AM TOTALLY NOT A ROBOT.","Pretty good.","Do me a flavor and send an email my way.","I\u2019m ugly but at least my eyes are green.","You should give me a job.","I\u2019m probably locked in my room playing with LEGO.","I don\u2019t even see the code. All I see is blonde, brunette, redhead.","It\u2019s a Unix system, I know this.","Did I mention that I would like a job?",":(){:|:&};:\ufeff",
"One job please!","Some days even my lucky rocket ship underpants don\u2019t help.","Christopher Dombroccoli.","HTML is the best programming language.","People who put noses in smiley faces are heathens.",":-)","I'm a genius. I build robots for fun.","Programmer Extraordinaire.","I'm pretty sure we're all in a simulation.","My favorite color is orange.","Have a nice day!","I just finished a jigsaw puzzle. The package said 5+ years but it only took me 2 months.","It's a doggy dog world out there.",
"I should have bought Bitcoin.","I use <i>coding</i> and <i>algorithms</i> to solve problems.","The language I like to use most when programming is profanity.","I'm probably showing this to you during an interview.","if ( !isWorking() ) { <br>&emsp;work();<br>}","Arrays should start at 2.",'"This shouldn\'t be working."'],A=[];
function C(){var a=document.getElementById("ticker");if(a.parentElement.querySelector(":hover")!==a){a.className+="fade";0==w.length&&(w=A,A=[]);var e=w.splice(Math.floor(Math.random()*w.length),1);A.push(e);var c=Math.floor(1E3*parseFloat(window.getComputedStyle(a).transitionDuration));setTimeout(function(){a.classList.remove("fade");a.innerHTML=e},c)}}var D;window.onload=function(){setInterval(C,3E3);D=document.getElementsByClassName("scrollfade")};
window.onscroll=function(){if(D)for(var a=0;a<D.length;a++){var e=D[a],c=3*e.offsetHeight;c=(c-pageYOffset)/c;e.style.opacity=0>c?0:1<c?1:c*c}};
window.addEventListener("load",function(){function a(a,c){var e=new Image,f=q.dataset.src;e.onload=function(){a.parent?a.parent.replaceChild(e,a):a.src=f;c&&c(a)};e.src=f}for(var e=document.getElementsByClassName("slideshow"),c=0;c<e.length;c++){var f=e[c];f.index=0;f.a=0;var k=document.createElement("div");k.className+="selectors";var l=document.createElement("a");l.classList.toggle("prev");l.classList.toggle("selector");l.innerHTML="&#10094;";l.onclick=function(){var a=f;return function(){E(a,--a.index)}}();
k.appendChild(l);l=f.getElementsByClassName("slide").length;for(var n=0;n<l;n++){var g=document.createElement("a");g.classList.toggle("selector");g.index=n;g.innerText=n;g.onclick=function(){var a=f,c=n;return function(){a.index=c;E(a,c)}}();k.appendChild(g)}l=document.createElement("a");l.classList.toggle("next");l.classList.toggle("selector");l.innerHTML="&#10095;";l.onclick=function(){var a=f;return function(){E(a,++a.index)}}();k.appendChild(l);f.appendChild(k);k=document.createElement("div");
k.classList.toggle("caption");f.appendChild(k);E(f,0)}e=document.getElementsByTagName("img");for(c=0;c<e.length;c++){var q=e[c];q.dataset.src?a(q,function(a){a.style.filter="unset"}):q.style.filter="unset"}});
function E(a,e){var c=a.getElementsByClassName("slide"),f=c.length;e=(e%f+f)%f;f=c[e];c[a.a].style.display="";f.style.display="block";var k=a.getElementsByClassName("caption");for(c=0;c<k.length;c++)k[c].innerHTML=f.dataset.caption;f=a.getElementsByClassName("selectors");for(c=0;c<f.length;c++)k=f[c].getElementsByClassName("selector"),k[a.a+1].classList.remove("selectorActive"),k[e+1].classList.add("selectorActive");a.a=e};